// frontend/src/pages/Jobs.tsx
import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { fetchJobs, toggleJob, triggerJob } from '../api/cron'
import type { CronJob } from '../types'
import dayjs from 'dayjs'

export default function Jobs() {
  const [jobs, setJobs] = useState<CronJob[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    loadJobs()
  }, [])

  async function loadJobs() {
    setLoading(true)
    try {
      const data = await fetchJobs()
      setJobs(data)
    } catch (error) {
      console.error('加载任务失败:', error)
    } finally {
      setLoading(false)
    }
  }

  function formatTime(timestamp?: number) {
    if (!timestamp) return '未执行'
    return dayjs(timestamp).format('YYYY-MM-DD HH:mm:ss')
  }

  async function handleToggle(jobId: string, currentStatus: boolean) {
    try {
      await toggleJob(jobId, !currentStatus)
      setJobs(jobs.map(job => 
        job.id === jobId ? { ...job, enabled: !currentStatus } : job
      ))
    } catch (error) {
      console.error('切换状态失败:', error)
    }
  }

  async function handleTrigger(jobId: string) {
    try {
      await triggerJob(jobId)
      alert('任务已触发！')
      loadJobs()
    } catch (error) {
      console.error('触发任务失败:', error)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600"></div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold text-gray-900">📋 任务列表</h2>
        <button onClick={loadJobs} className="btn-secondary">
          🔄 刷新
        </button>
      </div>

      <div className="space-y-4">
        {jobs.map(job => (
          <div key={job.id} className="card">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <div className="text-4xl">
                  {job.enabled ? '✅' : '⏸️'}
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-gray-900">{job.name}</h3>
                  <p className="text-sm text-gray-500 font-mono">{job.id}</p>
                  <p className="text-sm text-gray-500 mt-1">
                    调度: 
                    <span className="ml-1">
                      {job.schedule.kind === 'cron' 
                        ? `${job.schedule.expr} (${job.schedule.tz})` 
                        : `每 ${job.schedule.everyMs} 毫秒`
                      }
                    </span>
                  </p>
                </div>
              </div>
              
              <div className="flex items-center space-x-3">
                <button 
                  onClick={() => handleToggle(job.id, job.enabled)}
                  className={job.enabled ? 'btn-warning' : 'btn-success'}
                >
                  {job.enabled ? '⏸️ 禁用' : '▶️ 启用'}
                </button>
                
                <button 
                  onClick={() => handleTrigger(job.id)}
                  className="btn-primary"
                >
                  🚀 触发
                </button>
                
                <Link 
                  to={`/jobs/${job.id}`}
                  className="btn-secondary"
                >
                  📊 详情
                </Link>
              </div>
            </div>

            {/* 任务状态信息 */}
            <div className="mt-4 pt-4 border-t border-gray-200">
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div>
                  <span className="text-gray-500">上次执行:</span>
                  <span className="ml-2 font-medium">
                    {formatTime(job.state?.lastRunAtMs)}
                  </span>
                </div>
                <div>
                  <span className="text-gray-500">状态:</span>
                  <span className={`ml-2 font-medium ${job.state?.lastRunStatus === 'ok' ? 'text-green-600' : 'text-red-600'}`}>
                    {job.state?.lastRunStatus === 'ok' ? '✅ 成功' : '❌ 失败'}
                  </span>
                </div>
                <div>
                  <span className="text-gray-500">下次执行:</span>
                  <span className="ml-2 font-medium">
                    {formatTime(job.state?.nextRunAtMs)}
                  </span>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// frontend/src/views/Jobs.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useCronStore } from '../stores/cron'
import { storeToRefs } from 'pinia'

const store = useCronStore()
const { jobs, loading } = storeToRefs(store)

onMounted(() => {
  store.loadJobs()
})

function formatTime(timestamp?: number) {
  if (!timestamp) return '未执行'
  return new Date(timestamp).toLocaleString('zh-CN')
}

async function toggleJob(jobId: string, currentStatus: boolean) {
  await store.toggleJobStatus(jobId, !currentStatus)
}

async function triggerJob(jobId: string) {
  await store.triggerJobExecution(jobId)
  alert('任务已触发！')
}
</script>

<template>
  <div class="space-y-6">
    <div class="flex justify-between items-center">
      <h2 class="text-2xl font-bold text-gray-900">📋 任务列表</h2>
      <button @click="store.loadJobs()" class="btn-secondary">
        🔄 刷新
      </button>
    </div>

    <div v-if="loading" class="text-center py-8">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600 mx-auto"></div>
      <p class="mt-2 text-gray-500">加载中...</p>
    </div>

    <div v-else class="space-y-4">
      <div 
        v-for="job in jobs" 
        :key="job.id"
        class="card"
      >
        <div class="flex items-center justify-between">
          <div class="flex items-center space-x-4">
            <div class="text-3xl">
              {{ job.enabled ? '✅' : '⏸️' }}
            </div>
            <div>
              <h3 class="text-lg font-semibold text-gray-900">{{ job.name }}</h3>
              <p class="text-sm text-gray-500">
                ID: {{ job.id }}
              </p>
              <p class="text-sm text-gray-500">
                调度: 
                <span v-if="job.schedule.kind === 'cron'">
                  {{ job.schedule.expr }} ({{ job.schedule.tz }})
                </span>
                <span v-else>
                  每 {{ job.schedule.everyMs }} 毫秒
                </span>
              </p>
            </div>
          </div>
          
          <div class="flex items-center space-x-3">
            <button 
              @click="toggleJob(job.id, job.enabled)"
              :class="job.enabled ? 'bg-yellow-500 hover:bg-yellow-600' : 'bg-green-500 hover:bg-green-600'"
              class="text-white font-medium py-2 px-4 rounded-lg transition-colors duration-200"
            >
              {{ job.enabled ? '⏸️ 禁用' : '▶️ 启用' }}
            </button>
            
            <button 
              @click="triggerJob(job.id)"
              class="btn-primary"
            >
              🚀 触发
            </button>
            
            <router-link 
              :to="`/jobs/${job.id}`"
              class="btn-secondary"
            >
              📊 详情
            </router-link>
          </div>
        </div>

        <!-- 任务状态信息 -->
        <div class="mt-4 pt-4 border-t border-gray-200">
          <div class="grid grid-cols-3 gap-4 text-sm">
            <div>
              <span class="text-gray-500">上次执行:</span>
              <span class="ml-2 font-medium">
                {{ formatTime(job.state?.lastRunAtMs) }}
              </span>
            </div>
            <div>
              <span class="text-gray-500">状态:</span>
              <span :class="job.state?.lastRunStatus === 'ok' ? 'text-green-600' : 'text-red-600'" class="ml-2 font-medium">
                {{ job.state?.lastRunStatus === 'ok' ? '✅ 成功' : '❌ 失败' }}
              </span>
            </div>
            <div>
              <span class="text-gray-500">下次执行:</span>
              <span class="ml-2 font-medium">
                {{ formatTime(job.state?.nextRunAtMs) }}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
